### ISSUE TITLE
PHP versión

### ISSUE THREAD

**Issue by jacobo87** [jacobo87/IAW-Practica06#1]
Efectivamente revise el archivo de configuración de ```default``` y puse en la línea comentada la nueva versión de **php 7.4**, pero no en la de configuración.

                # With php7.4-fpm:
                fastcgi_pass unix:/run/php/php7.4-fpm.sock;

Tras corregirlo iba perfecto, podia entrar en index.php y phpmyadmin.

Muchas gracias. 
> Error por ir rápido.

**Comment by josejuansanchez** [comment]
Perfecto! Buen trabajo.
